language: java
jdk: oraclejdk7
env:
    matrix:
    - ANDROID_SDKS=android-16,addon-google_apis-google-16  ANDROID_TARGET=android-16  ANDROID_ABI=armeabi-v7a
#    - ANDROID_SDKS=android-10                ANDROID_TARGET=android-10  ANDROID_ABI=armeabi
#    - ANDROID_SDKS=sysimg-16                 ANDROID_TARGET=android-16  ANDROID_ABI=armeabi-v7a
#    - ANDROID_SDKS=android-17,sysimg-17      ANDROID_TARGET=android-17  ANDROID_ABI=armeabi-v7a
before_install:
    # Install base Android SDK
    - sudo apt-get update -qq
    - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
    - wget http://dl.google.com/android/android-sdk_r21.0.1-linux.tgz
    - tar xzf android-sdk_r21.0.1-linux.tgz
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
    # Install required Android components.
    - android update sdk --filter platform-tools,extra-android-support,extra-google-analytics_sdk_v2,extra-google-play_apk_expansion,extra-google-play_billing,extra-google-admob_ads_sdk,extra-google-gcm,extra-google-google_play_services,extra-google-play_licensing,android-17,$ANDROID_SDKS --no-ui --force
    # Setup maven-android-sdk-deployer
    - git clone --depth=50 --branch=master git://github.com/mosabua/maven-android-sdk-deployer.git mosabua/maven-android-sdk-deployer
    - cd mosabua/maven-android-sdk-deployer && mvn install -P 4.1
    # Create and start emulator
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &
before_script:
    # Make sure the emulator has started before running tests
    - ./wait_for_emulator
#script: mvn install -Pintegration-tests -Dandroid.device=test
script: mvn install
notifications:
  email:
    - open-networking@googlegroups.com
